//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SetSpeedCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(__CHECKFDCOMMAND_H__)
#define __CHECKFDCOMMAND_H__

#include"Transaction/MoveTaskManage/Command.h"

class CheckFDCommand : public Command
{
public:
    CheckFDCommand() { name = "CheckFireDoorCommand"; }
private:
    int exec();
};

#endif  //__CHECKFDCOMMAND_H__
