//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : Command.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_COMMAND_H)
#define _COMMAND_H

#include "base/SingleTon.h"
#include "ThirdParty/jsoncpp/json.h"
#include "MoveTaskComponent.h"
//执行
enum ExeResult 
{
	ST_SUCCESS =0, //成功
	ST_FAIL,       //失败
	ST_GOING,      //执行中
	ST_SLEEP       //休眠，尚未执行
};

enum POINT_NUM
{
    POINT_FIRST = 0,
    POINT_LAST,
};

class Command
{
public:
	Command();
	Command(Json::Value& paraJson);

    std::string name;       //命令名称
	Json::Value _paraJson; //动作参数

	int _exeRet;           //执行结果
	int _waitCnt;          //等待次数
	int _tryCnt;            //尝试次数
    int _exeStatus;    //动作状态机
	virtual int exec();
	Json::Value& getParaJson();
	void setParaJson(Json::Value& paraJson);
    Json::Value* getSharedParaJson();
    void setSharedParaJson(Json::Value* paraJson);
    void setSharedParent(MoveTaskComponent* parent);
	void setExeRet(int exeRet);
	int getExeRet();
	void initStatusPara();
	void clearTimer();
	int sleeepWaitTimeOut(int second);

private:
    MoveTaskComponent* _sharedParent;
};

#endif  //_COMMAND_H
