//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CommandFactory.h
//  @ Date : 2019-06-27
//  @ Author : 
//
//


#if !defined(_COMMANDFACTORY_H)
#define _COMMANDFACTORY_H

#include "Command.h"

enum COMMADNTYPE{
			CM_SET_SPEED =0,    //设置速度
			CM_RECOVER_SPEED,   //恢复默认速度 
			CM_CONTROL,         //控制
			CM_DRIVE_MODE,      //驱动模式设置
			CM_US_SWITCH,       //超声波开关
			CM_INFRARED_SWITCH, //红外开关
			CM_DOOR_SWITCH,     //防火门开关
			CM_GOTO,            //到达指定位置
			CM_FIND_NEAR_HALL,  //寻找霍尔开关
			CM_RECHARGE,        //充电
			CM_RUN_MODE,        //运行模式设置
			CM_UNDEFINED        //未定义
			};

class CommandFactory
{
public:
    Command createCommand(COMMADNTYPE type,Json::Value& paraJson);
};

#endif  //_COMMANDFACTORY_H
