//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : GotoCommand.h
//  @ Date : 2019-06-27
//  @ Author : ShunWang
//
//


#if !defined(_GOTOCOMMAND_H)
#define _GOTOCOMMAND_H

#include "Command.h"
enum GOTO_STATUS
{
	GOTO_ST_SNDCMD = 0,   //发送goto指令
	GOTO_ST_WAITRESULT    //等待执行结果
};

class GotoCommand : public Command
{
public:
    GotoCommand() { name = "GotoCommand"; }
private:
	int exec();
};

#endif  //_GOTOCOMMAND_H
