//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : GotoHome.h
//  @ Date : 2019-06-27
//  @ Author : ShunWang
//
//


#if !defined(_GOTOHOME_H)
#define _GOTOHOME_H

#include "Command.h"

enum GOTOHOME_STATUS
{
	GOTOHOME_ST_SNDCMD = 0,   //发送goto指令
	GOTOHOME_ST_WAITRESULT    //等待执行结果
};

class GotoHome : public Command
{
public:
    GotoHome() { name = "GotoHome"; }
private:
	int exec();
};

#endif  //_GOTOHOME_H