//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : HallDetCommand.h
//  @ Date : 2019-06-27
//  @ Author : ShunWang
//
//


#if !defined(_HALLDETCOMMAND_H)
#define _HALLDETCOMMAND_H

#include "Command.h"
#include "Driver/MotorDriver.h"
#include "Driver/HallDriver.h"

enum HALLDET_STATUS
{
    HALLDET_ST_WAIT = 0,     //等待结果
    HALLDET_ST_BACK500,      //前进到目标充电桩点
    HALLDET_ST_BACK500_WAIT, //等待结果
    HALLDET_ST_SLOW_DOWN,    //设置减速
	HALLDET_ST_GO,           //后退2M
	HALLDET_ST_GO_WAIT,      //等待结果
	HALLDET_ST_GO500,        //前进1M
	HALLDET_ST_GO500_WAIT,   //等待结果
    HALLDET_ST_SPEED_UP,     //恢复原始速度
};

class HallDetCommand : public Command
{
public:
    HallDetCommand() { name = "HallDetCommand"; }
private:
	int exec();
};

#endif  //_HALLDETCOMMAND_H
