//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : TakePhotoCommand.h
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//


#if !defined(_IMAGERECCOMMAND_H)
#define _IMAGERECCOMMAND_H

#include"Command.h"

#include "base/SingleTon.h"
#include <mutex>
#include <vector>

enum IMAGEREC_H_STATUS
{
	IMAGEREC_ST_BEGAIN = 0,   //转到预置点
	IMAGEREC_ST_FINSIH        //转到预置点
};

class ImageRecCommand : public Command
{
public:
    ImageRecCommand(){ name = "ImageRecCommand"; }
private:
    int exec();
    
};

#endif  //_IMAGERECCOMMAND_H
