//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : InfraredSwitchCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_INFRAREDSWITCHCOMMAND_H)
#define _INFRAREDSWITCHCOMMAND_H

#include "Command.h"

class InfraredSwitchCommand : public Command
{
public:
    InfraredSwitchCommand() { name = "InfraredSwitchCommand"; }
private:
	int exec();
};

#endif  //_INFRAREDSWITCHCOMMAND_H
