//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : MoveControlCommand.h
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//


#if !defined(_MOVECONTROLCOMMAND_H)
#define _MOVECONTROLCOMMAND_H

#include "Command.h"

enum MOVE_CONTROL_STATUS
{
    MOVE_COMMAND = 0,       //执行运动命令
    MOVE_CHECK,             //检查运动结果
    LIFT_CHECK,
};

class MoveControlCommand : public Command
{
public:
    MoveControlCommand() { name = "MoveControlCommand"; }
private:
	int exec();
};

#endif  //_MOVECONTROLCOMMAND_H
