//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : MoveTask.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_MOVETASK_H)
#define _MOVETASK_H

#include "MoveTaskComponent.h"
#include <vector>

class MoveTask : public MoveTaskComponent
{
public:
    MoveTask();

	int priority;
    void init();
	std::vector<MoveTaskComponent*> _taskComponents; 
    void add(MoveTaskComponent* taskComponent);
    void remove(MoveTaskComponent* taskComponent);
    std::vector<MoveTaskComponent*> getTaskComponents();
    MoveTaskComponent* findLeftMostChild();
    int getChildSize();
    MoveTaskComponent* getChild(int index);
};

#endif  //_MOVETASK_H
