//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : MoveException.h
//  @ Date : 2019-07-07
//  @ Author : Shunwang
//
//


#if !defined(_MOVEEXCEPTION_H)
#define _MOVEEXCEPTION_H
#include "base/Observers.h"
enum DEVCICE_TYPE //设备类型
{
  DEV_FOREWARD_INFRARED = 0,  //前红外
  DEV_BACK_INFRARED,          //后红外
  DEV_FOREWARD_USS,           //前超声波
  DEV_BACK_USS,               //后超声波
  DEV_DOWN_USS,
  DEV_FIREDOOR,               //防火门
  DEV_FOREWARD_MOTOR,         //前电机
  DEV_BACK_MOTOR,             //后电机
  DEV_TOTAL
};

class MoveException : public Observers
{
public:
	bool m_warmFlag[7]={false};
	static MoveException* getInstance();
	void init();
	bool getTotalMoveExcepFlag();
	void setForewardInfraredExcep(bool flag);
	void setForewardMotorExcep(bool flag);
	bool getForewardInfraredExcep();
	bool getForewardMotorExcep();
	void setForewardUSSExcep(bool flag);
	bool getForewardUSSExcep();
	void setBackUSSExcep(bool flag);
	void setBackMotorExcep(bool flag);
	bool getBackUSSExcep();
	bool getBackMotorExcep();
	void setBackInfraredExcep(bool flag);
	void setFireDoorExcep(bool flag);
	bool getBackInfraredExcep();
	bool getFireDoorExcep();
    void  update(int nSub);
	void setDownUSSExcep(bool flag);
};

#endif  //_MOVEEXCEPTION_H
