//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : PositionPlan.h
//  @ Date : 2019-10-30
//  @ Author : Huang, Bo
//
//


#if !defined(_POSITIONPLAN_H)
#define _POSITIONPLAN_H

#include <string>

class PositionPlan
{
public:
	int id;
	int robotId;
	std::string name;
	int functionId;
	int position;
	int goActionId;
	std::string goActionParam;
	int backActionId;
	std::string backActionParam;
    int mapId;
	int type;
	time_t findTime;
    int robot_position;

public:
    PositionPlan():robot_position(0){};
	void setId(int id);
	int getId();
	// void setRfidNum(int rfidNum);
	// int getRfidNum();
	void setName(std::string name);
	std::string getName();
	void setFunctionId(int functionId);
	int getFunctionId();
	void setPosition(int position);
	int getPosition();
	void setGoActionId(int goActionId);
	int getGoActionId();
	void setGoActionParam(std::string goActionParam);
	std::string getGoActionParam();
	void setBackActionId(int backActionId);
	int getBackActionId();
	void setBackActionParam(std::string backActionParam);
	std::string getBackActionParam();
	void setRobotId(int robotId);
	int getRobotId();
    void setMapId(int mapId);
    int getMapId();
	void setType(int type);
	int getType();
	void setFindTime(time_t time);
	time_t getFindTime();
};

#endif  //_POSITIONPLAN_H
