//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : PositionPlanServer.h
//  @ Date : 2019-10-30
//  @ Author : Huang, Bo
//
//


#if !defined(_POSITIONPLANSERVER_H)
#define _POSITIONPLANSERVER_H

#include "Transaction/MoveTaskManage/PositionPlan.h"
#include "Driver/MySQLDriver.h"
#include <list>

typedef Poco::Tuple<int, int, std::string, int, int, int, std::string, int, std::string, int> TuplePP;

class PositionPlanService{
	public:
		static int  queryPPById(int id,PositionPlan& pp);
    	// static int  queryPPByPosition(int position,PositionPlan& pp);
		static int queryPPListByRobotId(int robotId, std::list<PositionPlan>& pp);
		static int queryPPListByRobotMap(int robotId, int mapId, std::list<PositionPlan>& pp);
		static int queryPPByRobotPosition(int robotId, int position,PositionPlan& pp);
    	static void insertSelective(PositionPlan pp);
    	static void updatePositionPlan(PositionPlan pp);
		static void deletePPById(int id);
		static void deletePPByRobotId(int robotId);
};

#endif  //_POSITIONPLANSERVER_H
