//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : PositionMove.h
//  @ Date : 2019-10-30
//  @ Author : Huang, Bo
//
//


#if !defined(_POSITIONMOVE_H)
#define _POSITIONMOVE_H

#include <string>
#include <list>
#include <map>
#include "Transaction/MoveTaskManage/PositionPlanService.h"
#include "Transaction/MoveTaskManage/PositionPlan.h"
#include "base/SingleTon.h"

class PositionMove
{
public:
	// std::map<int, PositionPlan> m_PPMap;
    std::list<PositionPlan> m_PosPlan;
    int m_RobotId;
    int m_nMapId;
	bool m_ThreadRun;
	bool m_ready;
   
public:
	~PositionMove();
    static PositionMove *getInstance();
    int init();
	// void setRfidNum(int rfidNum);
	// int getRfidNum();
	static void movementTrigger(PositionMove* posMove);
	int updatePosPlan();
};

#endif  //_POSITIONMOVE_H
