//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : GotoCommand.h
//  @ Date : 2019-06-27
//  @ Author : ShunWang
//
//


#if !defined(_PTZARMCOMMAND_H)
#define _PTZARMCOMMAND_H

#include"Transaction/MoveTaskManage/Command.h"

enum PTZARM_STATUS
{
	ROTLIFT_ST_BEGAIN = 0,   //转动云台升降臂
	ROTLIFT_ST_WAIT,         //等待
	ROTLIFT_ST_CAPTURE,      //结束
    PTZ_ST_WAIT,
	ROTLIFT_ST_SUCCESS
};

class PtzArmCommand : public Command
{
public:
    PtzArmCommand() { name = "PtzArmCommand"; }
private:
	int exec();
};

#endif  //_PTZARMCOMMAND_H
