//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : PtzRotateCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_PTZROTATECOMMAND_H)
#define _PTZROTATECOMMAND_H

#include"Command.h"

enum ROTATE_STATUS
{
    ROTATE_ST_START = 0, //开始旋转
	ROTATE_ST_WAIT, //等待
	ROTATE_ST_FINISH    //旋转完成
};


class PtzRotateCommand : public Command
{
public:
    PtzRotateCommand() { name = "PtzRotateCommand"; }
private:
    int exec();
};

#endif  //_PTZROTATECOMMAND_H