//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : RechargeCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_RECHARGECOMMAND_H)
#define _RECHARGECOMMAND_H
#include"Transaction/MoveTaskManage/Command.h"
enum RECHARGE_STATUS
{
    RECHARGE_START = 0,
    RECHARGE_CHECK,
    /* RECHARGE_ST_RELAYOFF = 0, //关闭继电器
	RECHARGE_ST_RELAYON, //打开继电器
	RECHARGE_ST_DETECTCUR    //检测电流 */
};

enum RECHARGE_TYPE
{
    LOW_BATTERY_CHARGE = 0,
    MANUAL_CHARGE,
};

class RechargeCommand : public Command
{
public:
    RechargeCommand() { name = "RechargeCommand"; }
private:
    int exec();
};

#endif  //_RECHARGECOMMAND_H
