//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : RecordVideoCommand.h
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//


#if !defined(_RECORDVIDEOCOMMADN_H)
#define _RECORDVIDEOCOMMADN_H

#include"Command.h"

enum RECORDVIDEO_STATUS
{
	RECORDVIDEO_ST_BEGAIN = 0,   //转到预置点
    RECORDVIDEO_ST_WAIT,
	RECORDVIDEO_ST_FINSIH        //转到预置点
};

class RecordVideoCommand : public Command
{
public:
    RecordVideoCommand(){ name = "RecordVideoCommand"; }
private:
    int exec();
};

#endif  //_RECORDVIDEOCOMMADN_H