//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : RFIDService.h
//  @ Date : 2019-07-03
//  @ Author : ShunWang
//
//


#if !defined(_RFIDSERVICE_H)
#define _RFIDSERVICE_H

#include "RFID.h"
#include "Driver/MySQLDriver.h"
#include <list>

typedef Poco::Tuple<int, int64_t, int> TupleRFID;


class RFIDService
{
public:
  static int  queryRFIDById(int id,RFID& rfid);
  static int  queryRFIDByRfidNum(long long rfidNum,RFID& rfid);
  static int queryRFIDListByRobotId(int robotId,std::list<RFID>& rfids);
  static int queryRFIDListByMapId(uint32_t mapId, std::list<RFID>& rfids);
  static void insertSelective(RFID rfid);
  static void updateRFID(RFID rfid);
  static bool updateRFIDbyMapId(RFID rfid, uint32_t mapId);

  static void deleteRFIDById(int id);
  static void deleteRFIDByRobotId(int robotId);
  static bool deleteRFIDByMapId(uint32_t mapId);
  static void deleteRFID();

  static void updateRFIDPos(int nRobotID, long long RFIDNum, int nPos);
};

#endif  //_RFIDSERVICE_H
