//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SetMaxCurrentCommand.h
//  @ Date : 2020-04-19
//  @ Author : Jin.Jiang
//
//


#ifndef _SETMAXCURRENTCOMMAND_H
#define _SETMAXCURRENTCOMMAND_H


#include"Transaction/MoveTaskManage/Command.h"


class SetMaxCurrentCommand : public Command
{
public:
    SetMaxCurrentCommand() { name = "SetMaxCurrentCommand"; }
private:
    int exec();
};

#endif  //_SETMAXCURRENTCOMMAND_H
