//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SetSpeedCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_SETSPEEDCOMMAND_H)
#define _SETSPEEDCOMMAND_H

#include"Transaction/MoveTaskManage/Command.h"

class SetSpeedCommand : public Command
{
public:
    SetSpeedCommand() { name = "SetSpeedCommand"; }
private:
    int exec();
};

#endif  //_SETSPEEDCOMMAND_H
