//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SQLInsertCommand.h
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//


#if !defined(SQLINSERTCOMMAND)
#define SQLINSERTCOMMAND

#include"Command.h"

enum INSERT_STATUS
{
	INSERT_ST_BEGAIN = 0,   //转到预置点
	INSERT_ST_FINSIH        //转到预置点
};

class SQLInsertCommand : public Command
{
public:
    SQLInsertCommand(){ name = "SQLInsertCommand"; }
private:
    int exec();
};

#endif  //SQLINSERTCOMMAND