//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SetSpeedCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_SQLOPERATIONCOMMAND_H)
#define _SQLOPERATIONCOMMAND_H

#include "Transaction/MoveTaskManage/Command.h"

#define SQL_ADD_EXEC_RESULT 0

class SQLOperationCommand : public Command
{
public:
    SQLOperationCommand() { name = "SQLOperationCommand"; }
private:
    int exec();
};

#endif
