//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : GotoCommand.h
//  @ Date : 2019-06-27
//  @ Author : ShunWang
//
//


#if !defined(_T7ACHARGECOMMAND_H)
#define _T7ACHARGECOMMAND_H

#include "Command.h"
#include "RechargeCommand.h"
enum T7ACHARGE_STATUS
{
	T7ACHARGE_ST_SNDCMD = 0,    //发送goto指令
	T7ACHAGRE_ST_WAITRESULT,    //等待goto结果
    T7ACHAGRE_ST_CHARGERESULT,  //等待充电结果
    T7ACHAGRE_ST_FAILED,        //充电失败
    T7ACHAGRE_ST_STEPBACK,      //失败后倒车
    T7ACHAGRE_ST_STEPBACKRESULT
};

class T7AChargeCommand : public Command
{
public:
    T7AChargeCommand() { name = "T7AChargeCommand"; }
private:
	int exec();
};

#endif  //_T7ACHARGECOMMAND_H