//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : TakePhotoCommand.h
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//


#if !defined(_TAKEPHOTOCOMMAND_H)
#define _TAKEPHOTOCOMMAND_H

#include"Command.h"

enum TAKEPHO_STATUS
{
	TAKEPHO_ST_BEGAIN = 0,   //转到预置点
	TAKEPHO_ST_FINSIH        //转到预置点
};

class TakePhotoCommand : public Command
{
public:
    TakePhotoCommand(){ name = "TakePhotoCommand"; }
private:
    int exec();
};

#endif  //_TAKEPHOTOCOMMAND_H