//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : USSetThresholdCommand.h
//  @ Date : 2020-03-31
//  @ Author : XQ.Wang
//
//


#ifndef _USSETTHRESHOLDCOMMAND_H
#define _USSETTHRESHOLDCOMMAND_H


#include"Transaction/MoveTaskManage/Command.h"


class USSetThresholdCommand : public Command
{
public:
    USSetThresholdCommand() { name = "USSetThresholdCommand"; }
private:
    int exec();
};

#endif  //_USSETTHRESHOLDCOMMAND_H
