//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : USSwitchCommand.h
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#if !defined(_USSWITCHCOMMAND_H)
#define _USSWITCHCOMMAND_H

#include"Transaction/MoveTaskManage/Command.h"

class USSwitchCommand : public Command
{
public:
    USSwitchCommand() { name = "USSwitchCommand"; }
private:
    int exec();
};

#endif  //_USSWITCHCOMMAND_H
