//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CommandFactory.cpp
//  @ Date : 2019-06-27
//  @ Author : 
//
//


#include "CommandFactory.h"
#include "Command.h"

Command CommandFactory::createCommand(COMMADNTYPE type,Json::Value& paraJson)
{
//	switch(type)
//	{
//        case CM_SET_SPEED:
//		{
//            return new SetSpeedCommand(paraJson);
//		}
//    case CM_RECOVER_SPEED:
//		{
//            return new RecoverSpeedCommand(paraJson);
//		}
//    case CM_CONTROL:
//		{
//            return new ControlCommand(paraJson);
//		}
//    case CM_DRIVE_MODE:
//		{
//            return new DriveModeCommand(paraJson);
//		}
//        case CM_US_SWITCH:
//		{
//			return new USSwitchCommand(paraJson);
//		}
//		case CM_INFRARED_SWITCH:
//		{
//			return new InfraredSwitchCommand(paraJson);
//		}
//		case CM_DOOR_SWITCH:
//		{
//			return new DoorSwitchCommand(paraJson);
//		}
//		case CM_RECHARGE:
//		{
//			return new RechargeCommand(paraJson);
//		}
//		case CM_GOTO:
//		{
//			return new GotoCommand(paraJson);
//		}
//		case CM_FIND_NEAR_HALL:
//		{
//			return new HallDetCommand(paraJson);
//		}
//		case CM_RUN_MODE:
//		{
//			return new RunModeCommand(paraJson);
//		}
//		default:
//		{
//			return NULL;
//		}
//	}
}

