//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : DoorSwitchCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "DoorSwitchCommand.h"
#include "Driver/FireDoorDriver.h"

int DoorSwitchCommand::exec(){
    int cmd = _paraJson["cmd"].asInt();
    std::string IP = _paraJson["doorIPs"].asString();
    int para = _paraJson["FDValue"].asInt();
    int ret = 0;

    FireDoorDriver* fdDriver = FireDoorDriver::getInstance();

    printf("_exeRet = %d, __FILE__ =%s, __LINE__=%d\n",_exeRet,__FILE__,__LINE__);

    if(_exeRet != ST_SUCCESS && _exeRet != ST_FAIL){
        switch(cmd){
            case CLOSE_DOOR_CMD:
                ret = fdDriver->closeFireDoor(IP);
                if(ret == 0) _exeRet = ST_SUCCESS;
                else _exeRet = ST_FAIL;
                break;

            case OPEN_DOOR_CMD:
                ret = fdDriver->openFireDoor(IP);
                if(ret == 0) _exeRet = ST_SUCCESS;
                else _exeRet = ST_FAIL;
                break;

            default:
                _exeRet = ST_FAIL;
                break;
        }
    }
}
