//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : Command.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "Transaction/MoveTaskManage/Exception.h"

Exception::Exception(Json::Value& paraJson)
{
	_paraJson = paraJson;
    _sharedParent = NULL;
}

void Exception::setParaJson(Json::Value& paraJson)
{
	_paraJson = paraJson;
}

Json::Value& Exception::getParaJson()
{
	return _paraJson;
}

void Exception::setSharedParaJson(Json::Value* paraJson)
{
    if(_sharedParent == NULL) {
        printf("Exception::%s(), line = %d, parent is null!", __FUNCTION__, __LINE__);
        return;
    }
    _sharedParent->setParaJson(*paraJson);
}

Json::Value* Exception::getSharedParaJson()
{
    if(_sharedParent == NULL) {
        printf("Exception::%s(), line = %d, parent is null!", __FUNCTION__, __LINE__);
        return NULL;
    }
    return &_sharedParent->getParaJson();
}

void Exception::setSharedParent(MoveTaskComponent* parent)
{
    _sharedParent = parent;
}

