//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : TakePhotoCommand.cpp
//  @ Date : 2019-07-02
//  @ Author : ShunWang
//
//

#include "ImageRecCommand.h"
#include "Transaction/Robot.h"
#include <iostream>


const std::string LOG_TAG("root.ImageRec::");
extern ViewPointInfo patrolViewPointInfo;

int ImageRecCommand::exec()
{
    std::string logname = LOG_TAG + std::string(__FUNCTION__);
    auto logger = initLogger(logname);
    Robot *pRobot = Robot::getInstance();
    
	setExeRet(ST_GOING);
    switch(_exeStatus)
	{
		case IMAGEREC_ST_BEGAIN:
		{
            pRobot->m_pImageProcessManager->appendViewPointInfo(patrolViewPointInfo);
            _exeStatus = IMAGEREC_ST_FINSIH;
			break;
        }
        case IMAGEREC_ST_FINSIH:
		{
            setExeRet(ST_SUCCESS);
			break;
		}
		default:
		{
            setExeRet(ST_FAIL);
			break;
		}
	}
    return _exeRet;
}

