//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : InfraredSwitchCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "InfraredSwitchCommand.h"
#include "Robot.h"
int InfraredSwitchCommand::exec()
{
    int on_off = _paraJson["on-off"].asInt();
	Robot *robot = Robot::getInstance();	
}

