//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : USSwitchCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "LiftLockCommand.h"
#include "PowerDriver.h"

int LiftLockCommand::exec()
{
    int on_off = _paraJson["switch"].asInt();
	bool switchFlag = (bool)on_off;

	if (_exeRet != ST_SUCCESS && _exeRet != ST_FAIL) {
        printf("LiftLockCommand::exec(), Lock switch to %d\n", switchFlag);
        PowerDriver* powerDriver = PowerDriver::getInstance();
        powerDriver->switchBrake(switchFlag);
        _exeRet = ST_SUCCESS;
	}
	return _exeRet;

}

