//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : PositionPlan.cpp
//  @ Date : 2019-07-03
//  @ Author : ShunWang
//
//


#include "PositionPlan.h"

void PositionPlan::setId(int id)
{
	this->id = id;
}

int PositionPlan::getId()
{
	return id;
}

// void RFID::setRfidNum(int rfidNum)
// {
// 	this->rfidNum = rfidNum;
// }

// int RFID::getRfidNum()
// {
// 	return this->rfidNum;
// }

void PositionPlan::setName(std::string name)
{
	this->name = name;
}

std::string PositionPlan::getName()
{
	return this->name;
}

void PositionPlan::setFunctionId(int functionId)
{
	this->functionId = functionId;
}

int PositionPlan::getFunctionId()
{
	return functionId;
}

void PositionPlan::setPosition(int position)
{
	this->position = position;
}

int PositionPlan::getPosition()
{
	return position;
}

void PositionPlan::setGoActionId(int goActionId)
{
	this->goActionId= goActionId;
}

int PositionPlan::getGoActionId()
{
	return goActionId;
}

void PositionPlan::setGoActionParam(std::string goActionParam)
{
	this->goActionParam = goActionParam;
}

std::string PositionPlan::getGoActionParam()
{
	return goActionParam;
}

void PositionPlan::setBackActionId(int backActionId)
{
	this->backActionId = backActionId;
}

int PositionPlan::getBackActionId()
{
	return backActionId;
}

void PositionPlan::setBackActionParam(std::string backActionParam)
{
	this->backActionParam = backActionParam;
}

std::string PositionPlan::getBackActionParam()
{
	return backActionParam;
}

void PositionPlan::setRobotId(int robotId)
{
	this->robotId = robotId;
}

int PositionPlan::getRobotId()
{
	return robotId;
}

void PositionPlan::setMapId(int mapId)
{
    this->mapId = mapId;
}

int PositionPlan::getMapId()
{
    return mapId;
}



