//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : RecoverSpeedCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "RecoverSpeedCommand.h"
#include "Transaction/Motor.h"
#include "Transaction/SettingService.h"

int RecoverSpeedCommand::exec()
{
	Motor *motor = Motor::getInstance();
	if(_exeRet != ST_SUCCESS && _exeRet != ST_FAIL)
	{
		motor->m_fCurSpeed = motor->m_fPrevSpeed;
		int ret = motor->setSpeed(motor->m_fCurSpeed);
		if(0 == ret)
		{
			_exeRet = ST_SUCCESS;
		}
		else
		{
			_exeRet = ST_FAIL;
		}
	}
	return _exeRet;
}

