//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : USSetThresholdCommand.cpp
//  @ Date : 2020-03-31
//  @ Author : XQ.Wang
//
//


#include "SetMaxCurrentCommand.h"
#include "Transaction/Motor.h"

int SetMaxCurrentCommand::exec()
{
	int current = _paraJson["maxcurrent"].asInt();
	Motor* pMotor = Motor::getInstance();
	if(_exeRet != ST_SUCCESS && _exeRet != ST_FAIL){
		pMotor->setMaxCurrent(current);
		printf("SetMaxCurrentCommand::exec(), set current: %d\n", current);
		_exeRet = ST_SUCCESS;
	}
	return _exeRet;
}

