//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : SetSpeedCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "SetSpeedCommand.h"
#include "Transaction/Motor.h"
int SetSpeedCommand::exec()
{
	//解析JSON参数
	float speed = _paraJson["speed"].asFloat();
    Motor *motor = Motor::getInstance();
	if(_exeRet != ST_SUCCESS && _exeRet != ST_FAIL)
	{
		motor->m_fPrevSpeed = motor->m_fCurSpeed;
		motor->m_fCurSpeed = speed;
        int ret = motor->setSpeed(speed);
		
		if(0 == ret)
		{
			_exeRet = ST_SUCCESS;
		}
		else
		{
			_exeRet = ST_FAIL;
		}
	}
	return _exeRet;

}

