//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : T3C_SLAVE
//  @ File Name : USSwitchCommand.cpp
//  @ Date : 2019-06-25
//  @ Author : ShunWang
//
//


#include "USSwitchCommand.h"
#include "Transaction/RadarManager.h"
int USSwitchCommand::exec()
{
    int on_off = _paraJson["switch"].asInt();
	int pos = _paraJson["pos"].asInt();
	bool switchFlag;
    if(0 == on_off)
	{
		switchFlag = false;
	}
	else
	{
		switchFlag = true;
	}
    RadarManager* pRadar = RadarManager::getInstance();
	if(_exeRet != ST_SUCCESS && _exeRet != ST_FAIL){
        printf("USSwitchCommand::exec(), radar %d switch to %d\n", pos, switchFlag);
        //pRadar->setEnabled(pos, switchFlag);
        _exeRet =ST_SUCCESS;
	}
	return _exeRet;

}

